export const LETTER_SCORES: Record<string, number> = {
  a: 1,
  b: 3,
  c: 4,
  d: 4,
  e: 1,
  f: 5,
  g: 5,
  h: 3,
  i: 1,
  j: 7,
  k: 6,
  l: 2,
  m: 4,
  n: 2,
  o: 1,
  p: 4,
  q: 8,
  r: 8,
  s: 2,
  t: 1,
  u: 5,
  v: 6,
  w: 6,
  x: 8,
  y: 7,
  z: 9,
};

export const QUESTION_TYPES = {
  START: 'START',
  CONTAIN: 'CONTAIN',
} as const;

export const GAME_STATUS = {
  PENDING: 'pending',
  IN_PROGRESS: 'in-progress',
  PAUSED: 'paused',
  COMPLETED: 'completed',
} as const;

export const ROUND_TYPE = {
  PRELIMINARY: 'preliminary',
  FINALS: 'finals',
} as const;

export const TIME_LIMITS = {
  START_QUESTION: 30, // seconds
  CONTAIN_QUESTION: 60, // seconds
} as const;

export const GAME_CONFIG = {
  QUESTIONS_PER_ROUND: 5,
  PRELIMINARY_TEAMS_PER_ROUND: -1, // unlimited
  FINALIST_COUNT: 7,
  AUTO_ADVANCE_QUESTION: false, // admin controls progression
} as const;

export const VALIDATION_RULES = {
  ONLY_ALPHABETS: true,
  NO_PLURALS: true,
  NO_ING_SUFFIX: true,
  NO_ED_SUFFIX: true,
  NO_ACRONYMS: true,
  NO_PROPER_NOUNS: true,
  NO_PROGRAMMING_LANGUAGES: true,
  MUST_BE_TECH_RELATED: true,
} as const;

export const PROGRAMMING_LANGUAGES = [
  'python',
  'java',
  'javascript',
  'typescript',
  'c',
  'cpp',
  'csharp',
  'php',
  'ruby',
  'go',
  'rust',
  'kotlin',
  'swift',
  'scala',
  'perl',
  'julia',
  'r',
  'matlab',
  'groovy',
  'clojure',
  'haskell',
  'lisp',
  'elixir',
  'erlang',
  'lua',
  'dart',
  'objective-c',
  'vb',
  'visual basic',
  'cobol',
  'fortran',
  'assembly',
  'bash',
  'shell',
  'sql',
  'html',
  'css',
  'xml',
  'json',
  'yaml',
  'toml',
  'markdown',
];

export const TECH_GLOSSARY = [
  // Network & Internet
  'algorithm',
  'bandwidth',
  'cache',
  'database',
  'encryption',
  'firewall',
  'gateway',
  'hash',
  'interface',
  'jitter',
  'kernel',
  'latency',
  'middleware',
  'node',
  'oracle',
  'packet',
  'query',
  'router',
  'server',
  'token',
  'upload',
  'virtual',
  'webcam',
  'xmit',
  'yield',
  'zone',

  // Programming
  'array',
  'boolean',
  'class',
  'debug',
  'enum',
  'function',
  'generic',
  'heap',
  'inheritance',
  'loop',
  'method',
  'namespace',
  'object',
  'pointer',
  'recursion',
  'stack',
  'struct',
  'template',
  'variable',
  'widget',

  // Security
  'authentication',
  'authorization',
  'certificate',
  'cipher',
  'credential',
  'denial',
  'exploit',
  'firewall',
  'gateway',
  'intrusion',

  // Hardware
  'accelerator',
  'bandwidth',
  'buffer',
  'cache',
  'chip',
  'controller',
  'device',
  'driver',
  'firmware',
  'graphics',
  'hardware',
  'interrupt',
  'motherboard',
  'peripheral',
  'processor',
  'register',
  'sensor',
  'storage',
  'throughput',
  'transistor',

  // Data & Storage
  'backup',
  'blob',
  'bucket',
  'cluster',
  'column',
  'database',
  'dataset',
  'index',
  'index',
  'key',
  'partition',
  'queue',
  'record',
  'replica',
  'repository',
  'schema',
  'shard',
  'snapshot',
  'table',
  'tuple',
  'transaction',
  'warehouse',

  // Web & Cloud
  'api',
  'application',
  'artifact',
  'autoscale',
  'azure',
  'backend',
  'container',
  'deployment',
  'docker',
  'endpoint',
  'frontend',
  'graphql',
  'host',
  'instance',
  'kubernetes',
  'load',
  'microservice',
  'orchestration',
  'pod',
  'repository',
  'rest',
  'scalability',
  'serverless',
  'service',
  'webhook',

  // AI & ML
  'activation',
  'algorithm',
  'artificial',
  'backpropagation',
  'batch',
  'bias',
  'classification',
  'cluster',
  'convergence',
  'dataset',
  'deep',
  'dense',
  'dropout',
  'epoch',
  'feature',
  'gradient',
  'hyperparameter',
  'inference',
  'intelligence',
  'layer',
  'learning',
  'loss',
  'machine',
  'metric',
  'model',
  'neural',
  'neuron',
  'network',
  'optimization',
  'overfitting',
  'parameter',
  'pooling',
  'prediction',
  'regression',
  'regularization',
  'reinforcement',
  'sampling',
  'scale',
  'supervised',
  'tensor',
  'training',
  'transfer',
  'underfitting',
  'unsupervised',
  'weight',

  // DevOps & Infrastructure
  'ansible',
  'automation',
  'build',
  'ci',
  'cd',
  'cluster',
  'compute',
  'configure',
  'container',
  'deploy',
  'devops',
  'docker',
  'environment',
  'github',
  'gitlab',
  'infrastructure',
  'instance',
  'integration',
  'jenkins',
  'kubernetes',
  'loadbalance',
  'monitoring',
  'orchestration',
  'pipeline',
  'provisioning',
  'release',
  'repository',
  'scale',
  'terraform',
  'testing',
  'vagrant',
  'virtualization',
  'workflow',

  // Cybersecurity
  'attack',
  'authentication',
  'backdoor',
  'botnet',
  'breach',
  'brute',
  'buffer',
  'certificate',
  'cipher',
  'compliance',
  'cryptography',
  'ddos',
  'decryption',
  'defense',
  'denial',
  'detection',
  'encryption',
  'exploit',
  'firewall',
  'forensic',
  'hash',
  'honeypot',
  'infiltration',
  'intrusion',
  'key',
  'malware',
  'penetration',
  'phishing',
  'plaintext',
  'privilege',
  'protection',
  'protocol',
  'ransomware',
  'reverse',
  'sandbox',
  'scanning',
  'signature',
  'ssl',
  'threat',
  'tls',
  'trojan',
  'tunnel',
  'vulnerability',
  'virus',
  'worm',

  // Protocols & Standards
  'arp',
  'bgp',
  'dns',
  'dhcp',
  'ftp',
  'http',
  'https',
  'icmp',
  'igmp',
  'imap',
  'ip',
  'ipv4',
  'ipv6',
  'irc',
  'iscsi',
  'ldap',
  'mqtt',
  'ntp',
  'ospf',
  'pftp',
  'pop',
  'quic',
  'rtp',
  'sip',
  'smtp',
  'snmp',
  'ssh',
  'tcp',
  'telnet',
  'tftp',
  'udp',
  'voip',
  'xmpp',

  // Frameworks & Libraries
  'angular',
  'bootstrap',
  'django',
  'express',
  'fastapi',
  'flask',
  'gatsby',
  'laravel',
  'nextjs',
  'nuxt',
  'react',
  'redux',
  'spring',
  'tensorflow',
  'torch',
  'vue',
  'webpack',

  // Tools & Technologies
  'ansible',
  'atom',
  'aws',
  'azure',
  'bash',
  'bitbucket',
  'cmake',
  'cygwin',
  'docker',
  'eclipse',
  'emacs',
  'figma',
  'gcp',
  'git',
  'github',
  'gitlab',
  'gradle',
  'grafana',
  'grep',
  'hadoop',
  'heroku',
  'intellij',
  'jenkins',
  'jira',
  'kafka',
  'kubernetes',
  'latex',
  'linker',
  'linux',
  'maven',
  'netcat',
  'nginx',
  'npm',
  'opengl',
  'openssl',
  'pandas',
  'postman',
  'postgresql',
  'prometheus',
  'puppet',
  'radeon',
  'redis',
  'splunk',
  'sublime',
  'swagger',
  'terraform',
  'visual',
  'vscode',
  'webpack',
  'xcode',
  'yarn',

  // General IT Terms
  'abort',
  'access',
  'address',
  'allocation',
  'anchor',
  'application',
  'architecture',
  'archive',
  'argument',
  'array',
  'ascii',
  'assertion',
  'assignment',
  'asynchronous',
  'attach',
  'attribute',
  'audit',
  'authentication',
  'authorization',
  'autopsy',
  'availability',
  'backlog',
  'bandwidth',
  'batch',
  'beacon',
  'benchmark',
  'binary',
  'binding',
  'bitmap',
  'blacklist',
  'block',
  'bloom',
  'bootstrap',
  'bottleneck',
  'bounce',
  'boundary',
  'breakpoint',
  'bridge',
  'broadcast',
  'broker',
  'browse',
  'buffer',
  'bundle',
  'bus',
  'byte',
  'cache',
  'callback',
  'calibration',
  'campaign',
  'capacity',
  'capture',
  'cascade',
  'catalog',
  'category',
  'ceiling',
  'certificate',
  'checkpoint',
  'checksum',
  'circuit',
  'citation',
  'class',
  'classification',
  'cleanup',
  'client',
  'clipboard',
  'closure',
  'cluster',
  'coalesce',
  'code',
  'codec',
  'coherence',
  'collision',
  'command',
  'comment',
  'commit',
  'commodity',
  'common',
  'communication',
  'compact',
  'compatible',
  'compile',
  'compiler',
  'complement',
  'completion',
  'complex',
  'component',
  'compose',
  'composite',
  'compression',
  'computes',
  'concatenate',
  'concept',
  'concurrency',
  'concurrent',
  'condition',
  'configuration',
  'confluence',
  'congestion',
  'conjunction',
  'connection',
  'connector',
  'consensus',
  'consequence',
  'consistency',
  'console',
  'consolidate',
  'constant',
  'constraint',
  'construct',
  'constructor',
  'consumer',
  'context',
  'contextual',
  'continuation',
  'continuity',
  'continuous',
  'contract',
  'contrast',
  'contribution',
  'control',
  'convergence',
  'conversion',
  'convert',
  'convolution',
  'cooperation',
  'coordinate',
  'copy',
  'core',
  'correlate',
  'correspondence',
  'corroborate',
  'corrupt',
  'cost',
  'counter',
  'country',
  'coupling',
  'course',
  'coverage',
  'craft',
  'crash',
  'crawl',
  'creation',
  'credential',
  'criteria',
  'criterion',
  'critique',
  'cross',
  'crossing',
  'crowd',
  'cruise',
  'cryptographic',
  'crystalline',
  'cube',
  'cursor',
  'custom',
  'customization',
  'cycle',
  'cycling',
  
  // Adding more common words for better testing
  'anchor',
  'adapter',
  'analyze',
  'abstract',
  'append',
  'browser',
  'binary',
  'branch',
  'build',
  'bitmap',
  'breakpoint',
  'namespace',
  'network',
  'notation',
  'null',
  'decode',
  'define',
  'debug',
  'delete',
  'depth',
  'directive',
  'domain',
  'cluster',
  'circuit',
  'code',
  'command',
  'comment',
  'compile',
  'complete',
  'complex',
  'component',
  'condition',
  'constant',
  'consume',
  'copy',
  'count',
  'create',
  'loop',
  'load',
  'listen',
  'link',
  'logic',
];

export const COMMON_PROPER_NOUNS = [
  'google',
  'facebook',
  'microsoft',
  'apple',
  'amazon',
  'ibm',
  'oracle',
  'cisco',
  'intel',
  'nvidia',
  'amd',
  'linux',
  'ubuntu',
  'windows',
  'macos',
  'android',
  'ios',
  'github',
  'gitlab',
  'bitbucket',
];

export const ERROR_MESSAGES = {
  INVALID_WORD: 'Invalid word. Please check the rules.',
  WORD_TOO_SHORT: 'Word must be at least 2 characters.',
  NOT_TECH_RELATED: 'Word is not tech-related.',
  ALREADY_SUBMITTED: 'You have already submitted for this question.',
  TIME_EXPIRED: 'Time limit exceeded for this question.',
  INVALID_START_LETTER: 'Word does not start with the required letter.',
  INVALID_CONTAIN_LETTERS: 'Word does not contain all required letters.',
  CONTAINS_PLURAL: 'Plural words are not allowed.',
  ENDS_WITH_ING: 'Words ending with "ing" are not allowed.',
  ENDS_WITH_ED: 'Words ending with "ed" are not allowed.',
  IS_ACRONYM: 'Acronyms are not allowed.',
  IS_PROGRAMMING_LANGUAGE: 'Programming language names are not allowed.',
  IS_PROPER_NOUN: 'Proper nouns are not allowed.',
  CONTAINS_NON_ALPHABETS: 'Only alphabetic characters are allowed.',
  GAME_NOT_STARTED: 'Game has not started yet.',
  TEAM_NOT_FOUND: 'Team not found.',
  QUESTION_NOT_FOUND: 'Question not found.',
};

export const SUCCESS_MESSAGES = {
  WORD_VALID: 'Word is valid!',
  SUBMISSION_RECORDED: 'Your submission has been recorded.',
  LOGIN_SUCCESSFUL: 'Login successful.',
  REGISTRATION_SUCCESSFUL: 'Registration successful.',
};

export const SOCKET_EVENTS = {
  // Client -> Server
  JOIN_TEAM: 'join-team',
  SUBMIT_ANSWER: 'submit-answer',
  SKIP_QUESTION: 'skip-question',
  LEAVE_GAME: 'leave-game',

  // Server -> Client
  QUESTION_RELEASED: 'question-released',
  TIMER_UPDATE: 'timer-update',
  TIMER_START: 'timer-start',
  ANSWER_VALIDATED: 'answer-validated',
  LEADERBOARD_UPDATE: 'leaderboard-update',
  GAME_STATUS: 'game-status',
  ROUND_COMPLETE: 'round-complete',
  FINALS_ANNOUNCED: 'finals-announced',
  GAME_COMPLETE: 'game-complete',
  ERROR: 'error',
  DISCONNECT: 'disconnect',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;
